server=http://localhost:4111
apiVersion=/api/v1
backendVersion=with_database_with_fix

admin.username=admin
admin.password=admin

uiRemoteUrl=http://localhost:4444/wd/hub
uiBaseUrl=http://host.docker.internal:3000
browser=chrome
uiBrowserSize=1920x1080
uiTimeout=8000

db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres