server=http://localhost:4111
apiVersion=/api/v1

admin.username=admin
admin.password=admin

uiRemoteUrl=http://localhost:4444/wd/hub
uiBaseUrl=http://host.docker.internal:3000
browser=chrome
uiBrowserSize=1920x1080